PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?p (COUNT(?p) as ?ct) WHERE { 
	?s a owl:Class ;
       ?p ?o .
} 
GROUP BY (?p)
ORDER BY DESC(?ct)